name = "TaylorFinklea"
main = "./.output/server/index.mjs"
compatibility_date = "2023-02-06"
workers_dev = false
routes = [
	{ pattern = "taylor.finklea.ninja", zone_id = "7528aa9bce74b83fffde784914c78c4d", custom_domain = true },
]
[site]
bucket = ".output/public"
